### ISSUE TITLE
On-Page Checklist Review

### ISSUE THREAD

**Issue by jdabal** [9ci/9ci.github.io#18]
Will check robots/.txt, .htaccess, sitemap etc.

**Comment by WhitehatSEO-Expert** [comment]
9ci.com - On-Page SEO Checklist
https://docs.google.com/spreadsheets/d/1tJDocpPIycdUoq4nBOUM2MGyh_sZDJgd9g0LpSa85xY/edit#gid=692607886

**Comment by jdabal** [comment]
Please update the checklist document, wy do we still have 404 as red? We fixed them unless I'm missing something

**Comment by WhitehatSEO-Expert** [comment]
There are some more 404 error pages which still need to be fixed, that's why I left this as red.

**Comment by jdabal** [comment]
@sushantkumbhar9 
this is report I used to fix 4094s, i did all of them:

https://docs.google.com/spreadsheets/d/1mG-pNAagzdO06OihBbNPucoTu6pcVkNr9HmsQpvPxLA/edit#gid=1013734247


if there are more I need to know so I can fix.

**Comment by WhitehatSEO-Expert** [comment]
There are two new 404 errors, kindly fix these as well:

404 page
https://www.9ci.com/results

Link from
https://www.9ci.com/contact/

404 page
https://www.9ci.com/blog

Link from
https://www.9ci.com/blog/tag/collection-calculation/
https://www.9ci.com/blog/tag/lockbox/
https://www.9ci.com/blog/tag/productivity/
https://www.9ci.com/blog/tag/autocash/
https://www.9ci.com/blog/tag/ar-dashboard/
https://www.9ci.com/blog/tag/ai/

**Comment by jdabal** [comment]
Fixed, please review again and run your report

**Comment by WhitehatSEO-Expert** [comment]
now there is no 404 error
