### ISSUE TITLE
Need to process Single page implementation

### ISSUE THREAD

**Issue by sushantkumbhar9** [9ci/9ci.github.io#25]
Hi @jdabal 

Target page: https://www.9ci.com/solutions/auto-cash-cash-application/

Please update, meta tags, and other suggestions given on this Doc.

2020-06-22 - 9ci.com - Single Page Recommendation
https://docs.google.com/document/d/1Asronwsa65xDu8R5_Go2QedfX4q8xBvjHtBfGj9yNuU/edit#

**Comment by jdabal** [comment]
![image](https://user-images.githubusercontent.com/421237/85483496-859d1500-b58a-11ea-9e05-47458794db07.png)


![image](https://user-images.githubusercontent.com/421237/85483665-e4628e80-b58a-11ea-955d-6efcf09311b7.png)


![image](https://user-images.githubusercontent.com/421237/85483708-fd6b3f80-b58a-11ea-8b03-2e1081f06875.png)

**Comment by sushantkumbhar9** [comment]
@jdabal 

There are two pages with having the same content, need to apply 301 redirects over the following page

https://www.9ci.com/solutions/autocash/

to

https://www.9ci.com/solutions/auto-cash-cash-application/

**Comment by jdabal** [comment]
we talked about it, I prefer to remove one page.  In this case I will remove solutions/autocash

**Comment by sushantkumbhar9** [comment]
sure, we need to remove solutions/autocash and apply 301 redirects over it to solutions/auto-cash-cash-application/.

**Comment by jdabal** [comment]
done

**Comment by sushantkumbhar9** [comment]
Please apply 301 redirect
