### ISSUE TITLE
GTM setup

### ISSUE THREAD

**Issue by sushantkumbhar9** [9ci/9ci.github.io#26]
@jdabal  need to inject these Codes to the website

**Paste this code as high in the <head> of the page as possible:**
`
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-M26LTFR');</script>
`

**Additionally, paste this code immediately after the opening <body> tag:**
`
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-M26LTFR"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
`

**Comment by jdabal** [comment]
give me copy of page Source that you want it on, edit it with this code and attach a copy of html file here.
I don't know if I should put it on header or body. On main page 9ci.com or sub page

**Comment by WhitehatSEO-Expert** [comment]
Perfect!
